import type { SteamGame } from "@/types/steam";
import { headerImageUrl } from "@/lib/format";

const now = Math.floor(Date.now() / 1000);
const day = 86400;

export const MOCK_LIBRARY: SteamGame[] = [
  {
    appid: 1245620,
    name: "Elden Ring",
    playtimeForever: 3420,
    playtime2Weeks: 0,
    lastPlayed: now - 45 * day,
    headerImage: headerImageUrl(1245620),
    genres: ["Action", "RPG"],
    tags: ["Souls-like", "Open World", "Difficult"],
  },
  {
    appid: 413150,
    name: "Stardew Valley",
    playtimeForever: 2880,
    playtime2Weeks: 120,
    lastPlayed: now - 3 * day,
    headerImage: headerImageUrl(413150),
    genres: ["Indie", "Simulation", "RPG"],
    tags: ["Relaxing", "Farming", "Pixel Graphics"],
  },
  {
    appid: 1145360,
    name: "Hades",
    playtimeForever: 1560,
    playtime2Weeks: 0,
    lastPlayed: now - 90 * day,
    headerImage: headerImageUrl(1145360),
    genres: ["Action", "Indie", "RPG"],
    tags: ["Roguelike", "Story Rich", "Great Soundtrack"],
  },
  {
    appid: 367520,
    name: "Hollow Knight",
    playtimeForever: 0,
    lastPlayed: undefined,
    headerImage: headerImageUrl(367520),
    genres: ["Action", "Adventure", "Indie"],
    tags: ["Metroidvania", "Difficult", "Atmospheric"],
  },
  {
    appid: 1091500,
    name: "Cyberpunk 2077",
    playtimeForever: 4200,
    playtime2Weeks: 300,
    lastPlayed: now - 1 * day,
    headerImage: headerImageUrl(1091500),
    genres: ["RPG"],
    tags: ["Open World", "Cyberpunk", "Story Rich"],
  },
  {
    appid: 620,
    name: "Portal 2",
    playtimeForever: 480,
    playtime2Weeks: 0,
    lastPlayed: now - 180 * day,
    headerImage: headerImageUrl(620),
    genres: ["Action", "Adventure"],
    tags: ["Puzzle", "Co-op", "Sci-fi"],
  },
  {
    appid: 105600,
    name: "Terraria",
    playtimeForever: 960,
    playtime2Weeks: 0,
    lastPlayed: now - 120 * day,
    headerImage: headerImageUrl(105600),
    genres: ["Action", "Adventure", "Indie"],
    tags: ["Sandbox", "Crafting", "2D"],
  },
  {
    appid: 1174180,
    name: "Red Dead Redemption 2",
    playtimeForever: 0,
    lastPlayed: undefined,
    headerImage: headerImageUrl(1174180),
    genres: ["Action", "Adventure"],
    tags: ["Open World", "Western", "Story Rich"],
  },
  {
    appid: 252950,
    name: "Rocket League",
    playtimeForever: 720,
    playtime2Weeks: 60,
    lastPlayed: now - 5 * day,
    headerImage: headerImageUrl(252950),
    genres: ["Action", "Indie", "Sports"],
    tags: ["Multiplayer", "Competitive", "Fast-Paced"],
  },
  {
    appid: 1086940,
    name: "Baldur's Gate 3",
    playtimeForever: 5400,
    playtime2Weeks: 0,
    lastPlayed: now - 60 * day,
    headerImage: headerImageUrl(1086940),
    genres: ["RPG", "Strategy"],
    tags: ["Turn-Based", "Story Rich", "Character Customization"],
  },
  {
    appid: 4000,
    name: "Garry's Mod",
    playtimeForever: 180,
    playtime2Weeks: 0,
    lastPlayed: now - 365 * day,
    headerImage: headerImageUrl(4000),
    genres: ["Action", "Indie", "Simulation"],
    tags: ["Sandbox", "Moddable", "Multiplayer"],
  },
  {
    appid: 1794680,
    name: "Vampire Survivors",
    playtimeForever: 300,
    playtime2Weeks: 45,
    lastPlayed: now - 2 * day,
    headerImage: headerImageUrl(1794680),
    genres: ["Action", "Casual", "Indie"],
    tags: ["Roguelike", "Bullet Hell", "Pixel Graphics"],
  },
  {
    appid: 271590,
    name: "Grand Theft Auto V",
    playtimeForever: 2400,
    playtime2Weeks: 0,
    lastPlayed: now - 200 * day,
    headerImage: headerImageUrl(271590),
    genres: ["Action", "Adventure"],
    tags: ["Open World", "Crime", "Multiplayer"],
  },
  {
    appid: 236390,
    name: "War Thunder",
    playtimeForever: 45,
    playtime2Weeks: 0,
    lastPlayed: now - 30 * day,
    headerImage: headerImageUrl(236390),
    genres: ["Action", "Free to Play", "Simulation"],
    tags: ["Vehicular Combat", "Multiplayer", "WWII"],
  },
  {
    appid: 1623730,
    name: "Palworld",
    playtimeForever: 0,
    lastPlayed: undefined,
    headerImage: headerImageUrl(1623730),
    genres: ["Action", "Adventure", "Indie"],
    tags: ["Survival", "Crafting", "Open World"],
  },
];

export function getMockLibrary(): SteamGame[] {
  return MOCK_LIBRARY.map((g) => ({ ...g }));
}
